### PR TITLE
Added Binary_tree_is_symmetirc_or_not.cpp

### PR DESCRIPTION
**Pull request by ct-27**
Solution to check whether a given binary tree is symmetric tree or not.

### CODE REVIEW

**Review by abhi-shek421 — COMMENTED** [review]
Fix the code.

**Comment by ct-27** [comment]
@abhi-shek421 What do I need to fix? Are you talking about the driver code?

**Comment by abhilashmnair** [comment]
@ct-27 Yes add driver code.

**Comment by ct-27** [comment]
Done @abhilashmnair. Please check.

**Comment by abhilashmnair** [comment]
Thank you for your contribution @ct-27

**Pull request merged**
