### PR TITLE
Create Find First and Last Position of Element in Sorted Array using …

### PR DESCRIPTION
**Pull request by YushChaudhary**
…Python.py

### CODE REVIEW

**Comment by abhilashmnair** [comment]
Could you add more unique codes?

**Comment by YushChaudhary** [comment]
ok no problem is i need to change this code ?

**Comment by YushChaudhary** [comment]
Hey Abhilash can you explain a little bit what changes you need?

**Comment by abhilashmnair** [comment]
Add codes related to data structures (even an array manipulation code is accepted) or other algorithms. 😊

**Pull request closed without merging**
